// Auto-generated by CDK BucketDeployment — do not edit manually.
// For local development, fill in values below.
const C={region:'us-west-2',userPoolId:'',clientId:'',domain:'',turnstileSiteKey:''};
