{{- if .Values.gateway.enabled }}
apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: {{ include "openclaw-helm.fullname" . }}-tg
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openclaw-helm.labels" . | nindent 4 }}
spec:
  targetReference:
    name: {{ include "openclaw-helm.fullname" . }}
  defaultConfiguration:
    targetType: ip
{{- end }}
